var data = {
  "quantClassIDs": [
    "API-121",
    "API-126",
    "API-141",
    "API-148",
    "API-205",
    "API-302",
    "API-303",
    "API-304",
    "BGP-610",
    "DEV-130",
    "SUP-125",
    "SUP-572",
    "SUP-651",
    "API-135",
    "API-206",
    "BGP-620",
    "BGP-670",
    "DEV-115",
    "SUP-427",
    "SUP-450"
  ],
  "mldClassIDs": [
    "MLD-224",
    "MLD-310",
    "MLD-340",
    "MLD-601",
    "MLD-201",
    "MLD-500",
    "DPI-312M",
    "MLD-102M",
    "MLD-355M",
    "MLD-222M",
    "MLD-223M",
    "MLD-356M",
    "MLD-411M",
    "MLD-630M",
    "DPI-313M",
    "MLD-280",
    "DPI-365",
    "MLD-301",
    "MLD-304",
    "MLD-377",
    "MLD-412",
    "MLD-502",
    "MLD-602",
    "MLD-621",
    "MLD-635M"
  ],
  "politicalClassIDs": [
    "DPI-122",
    "DPI-132",
    "DPI-204",
    "DPI-305",
    "DPI-342",
    "DPI-391",
    "DPI-407",
    "DPI-415",
    "DPI-421",
    "DPI-440",
    "DPI-662",
    "IGA-103",
    "IGA-112",
    "DPI-120",
    "DPI-216",
    "DPI-218",
    "DPI-235",
    "DPI-242",
    "DPI-253",
    "DPI-337",
    "DPI-450",
    "DPI-460",
    "DPI-720",
    "IGA-220"
  ],

  "classes":
[
  {
    "Course ID": "API-101-Fall-B",
    "Course No": "API-101",
    "Section": "B",
    "Title": "Markets and Market Failure",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Janina Matuszeski",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-101-Fall-C",
    "Course No": "API-101",
    "Section": "C",
    "Title": "Markets and Market Failure",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "David Ellwood",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-101-Fall-D",
    "Course No": "API-101",
    "Section": "D",
    "Title": "Markets and Market Failure",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Pinar Dogan",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-101-Fall-Z",
    "Course No": "API-101",
    "Section": "Z",
    "Title": "Markets and Market Failure",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Christopher Avery",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-102-Spring-A",
    "Course No": "API-102",
    "Section": "A",
    "Title": "Economic Analysis of Public Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Mark Shepard",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-102-Spring-B",
    "Course No": "API-102",
    "Section": "B",
    "Title": "Economic Analysis of Public Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Joseph Aldy",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-102-Spring-I",
    "Course No": "API-102",
    "Section": "I",
    "Title": "Economic Analysis of Public Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Robert Lawrence, Jason Furman",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-102-Spring-Z",
    "Course No": "API-102",
    "Section": "Z",
    "Title": "Economic Analysis of Public Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Jeffrey Liebman",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-109-Fall-",
    "Course No": "API-109",
    "Section": null,
    "Title": "Advanced Microeconomic Analysis I",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Maciej Kotowski",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "API-110-Spring-",
    "Course No": "API-110",
    "Section": null,
    "Title": "Advanced Microeconomic  Analysis II",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Jie Bai",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "API-111-Fall-",
    "Course No": "API-111",
    "Section": null,
    "Title": "Microeconomic Theory I",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Maciej Kotowski",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "API-112-Spring-",
    "Course No": "API-112",
    "Section": null,
    "Title": "Microeconomic Theory II",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Christopher Avery",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "API-114-Fall-",
    "Course No": "API-114",
    "Section": null,
    "Title": "Econometric Methods for Applied Research I",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Steve Cicala",
    "Class Day": "T/Th",
    "Class Time": "1:00 PM-2:30 PM"
  },
  {
    "Course ID": "API-115-Spring-",
    "Course No": "API-115",
    "Section": null,
    "Title": "Econometric Methods for Applied Research II",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Joshua Goodman",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "API-119-Spring-",
    "Course No": "API-119",
    "Section": null,
    "Title": "Advanced Macroeconomics for the Open Economy II",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Filipe Campante, Jeffrey Frankel",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "API-120-Fall-",
    "Course No": "API-120",
    "Section": null,
    "Title": "Advanced Macroeconomics for the Open Economy I",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Jeffrey Frankel",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "API-121-Fall-",
    "Course No": "API-121",
    "Section": null,
    "Title": "Macroeconomic Theory and Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Karen Dynan",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "API-126-Fall-",
    "Course No": "API-126",
    "Section": null,
    "Title": "American Economic Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Lawrence H. Summers, Jeffrey Liebman, Martin Feldstein",
    "Class Day": "M/W/F",
    "Class Time": "11:00 AM-11:59 AM"
  },
  {
    "Course ID": "API-135-Spring-",
    "Course No": "API-135",
    "Section": null,
    "Title": "Fundamentals of Environmental Economics and Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Robert Stavins",
    "Class Day": "M/W/F",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "API-141-Fall-",
    "Course No": "API-141",
    "Section": null,
    "Title": "Finance",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Akash Deep",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "API-148-Fall-",
    "Course No": "API-148",
    "Section": null,
    "Title": "Advanced Risk Management and Infrastructure Finance",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Akash Deep",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-164-Spring-",
    "Course No": "API-164",
    "Section": null,
    "Title": "Energy Policy Analysis",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Joseph Aldy",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "API-166-Fall-",
    "Course No": "API-166",
    "Section": null,
    "Title": "Electricity Market Design",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "William Hogan",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-201-Fall-A",
    "Course No": "API-201",
    "Section": "A",
    "Title": "Quantitative Analysis and Empirical Methods",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Steve Cicala",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "API-201-Fall-C",
    "Course No": "API-201",
    "Section": "C",
    "Title": "Quantitative Analysis and Empirical Methods",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Dan Levy",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "API-201-Fall-D",
    "Course No": "API-201",
    "Section": "D",
    "Title": "Quantitative Analysis and Empirical Methods",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Theodore Svoronos",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "API-201-Fall-Z",
    "Course No": "API-201",
    "Section": "Z",
    "Title": "Quantitative Analysis and Empirical Methods",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Soroush Saghafian",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "API-202-Spring-A",
    "Course No": "API-202",
    "Section": "A",
    "Title": "Empirical Methods II",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Joshua Goodman",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-202-Spring-B",
    "Course No": "API-202",
    "Section": "B",
    "Title": "Empirical Methods II",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Miguel Santos",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-202-Spring-I",
    "Course No": "API-202",
    "Section": "I",
    "Title": "Empirical Methods II",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Anders Jensen",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-202-Spring-Z",
    "Course No": "API-202",
    "Section": "Z",
    "Title": "Empirical Methods II",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Gregory Bruich",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-205-Fall-",
    "Course No": "API-205",
    "Section": null,
    "Title": "Politics and Policies: What Can Data Tell Us?",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Deborah Hughes Hallett",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "API-206-Spring-",
    "Course No": "API-206",
    "Section": null,
    "Title": "Fundamentals of Program and Policy Evaluation",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Janina Matuszeski",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "API-209-Fall-",
    "Course No": "API-209",
    "Section": null,
    "Title": "Advanced Quantitative Methods I: Statistics",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Dan Levy",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "API-210-Spring-",
    "Course No": "API-210",
    "Section": null,
    "Title": "Advanced Quantitative Methods II: Econometric Methods",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Theodore Svoronos",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-211-Spring-",
    "Course No": "API-211",
    "Section": null,
    "Title": "Program Evaluation",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Thomas Kane",
    "Class Day": "M",
    "Class Time": "4:00 PM-6:59 PM"
  },
  {
    "Course ID": "API-302-Fall-",
    "Course No": "API-302",
    "Section": null,
    "Title": "Analytic Frameworks for Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Richard Zeckhauser",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "API-303-Fall-",
    "Course No": "API-303",
    "Section": null,
    "Title": "Game Theory and Strategic Decisions",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Pinar Dogan",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "API-304-Fall-",
    "Course No": "API-304",
    "Section": null,
    "Title": "Behavioral Economics and Public Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Brigitte Madrian",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "API-305-Spring-",
    "Course No": "API-305",
    "Section": null,
    "Title": "Behavioral Economics, Law and Public Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": null,
    "Class Day": "W",
    "Class Time": "3:00 PM-5:00 PM"
  },
  {
    "Course ID": "API-500M-Spring 2-A",
    "Course No": "API-500M",
    "Section": "A",
    "Title": "Spring Policy Exercise",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Sheila Burke",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "API-500M-Spring 2-B",
    "Course No": "API-500M",
    "Section": "B",
    "Title": "Spring Policy Exercise",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "John Donahue",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "API-500M-Spring 2-C",
    "Course No": "API-500M",
    "Section": "C",
    "Title": "Spring Policy Exercise",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Mark Fagan",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "API-500M-Spring 2-D",
    "Course No": "API-500M",
    "Section": "D",
    "Title": "Spring Policy Exercise",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "William Clark",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "API-901-Fall-",
    "Course No": "API-901",
    "Section": null,
    "Title": "Doctoral Research Seminar",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Matthew Baum",
    "Class Day": "T",
    "Class Time": "10:00 AM-12:00 PM"
  },
  {
    "Course ID": "API-902-Fall-",
    "Course No": "API-902",
    "Section": null,
    "Title": "Doctoral Research Seminar",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Richard Zeckhauser, Matthew Baum",
    "Class Day": "T",
    "Class Time": "2:00 PM-4:00 PM"
  },
  {
    "Course ID": "API-905Y-Year-",
    "Course No": "API-905Y",
    "Section": null,
    "Title": "Seminar on Environmental Economics and Policy",
    "Credits": "4.00",
    "Term": "Year",
    "Faculty": "Robert Stavins",
    "Class Day": "W",
    "Class Time": "4:15 PM-5:30 PM"
  },
  {
    "Course ID": "BGP-150Y-Year-",
    "Course No": "BGP-150Y",
    "Section": null,
    "Title": "Seminar: Business and Government",
    "Credits": "4.00",
    "Term": "Year",
    "Faculty": "John Haigh",
    "Class Day": "Th",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "BGP-235M-Fall 2-",
    "Course No": "BGP-235M",
    "Section": null,
    "Title": "Private Capital for Public Purpose: Impact Investing and Its Siblings",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "David Wood",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "BGP-238-Spring-",
    "Course No": "BGP-238",
    "Section": null,
    "Title": "Corporate Governance",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Andy Zelleke",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "BGP-264-Spring-",
    "Course No": "BGP-264",
    "Section": null,
    "Title": "Capital Markets Regulation",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Robert Glauber",
    "Class Day": "W",
    "Class Time": "5:00 PM-7:00 PM"
  },
  {
    "Course ID": "BGP-450M-January-",
    "Course No": "BGP-450M",
    "Section": null,
    "Title": "Globalization:  Business, Legal and Public Policy Issues",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Lewis Kaden",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "9:30 AM-12:30 PM"
  },
  {
    "Course ID": "BGP-510Y-Year-",
    "Course No": "BGP-510Y",
    "Section": null,
    "Title": "HKS-HBS Joint Degree First-Year Seminar",
    "Credits": "2.00",
    "Term": "Year",
    "Faculty": "Shawn Cole",
    "Class Day": "M",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "BGP-610-Fall-",
    "Course No": "BGP-610",
    "Section": null,
    "Title": "The Political Economy of Trade",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Robert Lawrence",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "BGP-620-Spring-",
    "Course No": "BGP-620",
    "Section": null,
    "Title": "International Macroeconomics",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Jeffrey Frankel",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "BGP-625-Fall-",
    "Course No": "BGP-625",
    "Section": null,
    "Title": "The Future of Globalization: Issues, Actors, and Decisions",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Lawrence H. Summers, Robert Lawrence",
    "Class Day": "T/Th",
    "Class Time": "10:00 AM-11:29 AM"
  },
  {
    "Course ID": "BGP-670-Spring-",
    "Course No": "BGP-670",
    "Section": null,
    "Title": "Financial Crises: Concepts and Evidence",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Carmen Reinhart",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DEV-101-Fall-",
    "Course No": "DEV-101",
    "Section": null,
    "Title": "Economic Development: Theory and Evidence",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Dani Rodrik, Lant Pritchett",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DEV-102-Spring-",
    "Course No": "DEV-102",
    "Section": null,
    "Title": "Economic Development: Using Analytical Frameworks for Smart Policy Design",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Asim Khwaja",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DEV-115-Spring-",
    "Course No": "DEV-115",
    "Section": null,
    "Title": "Using Data to Understand Good Governance",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Filipe Campante",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DEV-130-Fall-",
    "Course No": "DEV-130",
    "Section": null,
    "Title": "Why Are So Many Countries Poor, Volatile, and Unequal?",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Ricardo Hausmann",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "DEV-150Y-Year-",
    "Course No": "DEV-150Y",
    "Section": null,
    "Title": "Seminar: Political and Economic Development",
    "Credits": "4.00",
    "Term": "Year",
    "Faculty": "Ryan Sheely",
    "Class Day": "Th",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "DEV-209-Spring-",
    "Course No": "DEV-209",
    "Section": null,
    "Title": "Management, Finance, and Regulation of Public Infrastructure in Developing Countries",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Henry Lee",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DEV-210-Fall-",
    "Course No": "DEV-210",
    "Section": null,
    "Title": "Public Finance in Theory and Practice",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Jay Rosengard",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "DEV-233-Spring-",
    "Course No": "DEV-233",
    "Section": null,
    "Title": "Political Economy After the Crisis",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Dani Rodrik, Roberto Mangabeira Unger",
    "Class Day": "M",
    "Class Time": "1:00 PM-3:00 PM"
  },
  {
    "Course ID": "DEV-250Y-Year-A",
    "Course No": "DEV-250Y",
    "Section": "A",
    "Title": "Second-Year Policy Analysis Seminar",
    "Credits": "6.00",
    "Term": "Year",
    "Faculty": "Carmen Reinhart",
    "Class Day": "Th",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "DEV-250Y-Year-B",
    "Course No": "DEV-250Y",
    "Section": "B",
    "Title": "Second-Year Policy Analysis Seminar",
    "Credits": "6.00",
    "Term": "Year",
    "Faculty": "Rema Hanna",
    "Class Day": "Th",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "DEV-250Y-Year-C",
    "Course No": "DEV-250Y",
    "Section": "C",
    "Title": "Second-Year Policy Analysis Seminar",
    "Credits": "6.00",
    "Term": "Year",
    "Faculty": "Michael Walton",
    "Class Day": "Th",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "DEV-308-Spring-",
    "Course No": "DEV-308",
    "Section": null,
    "Title": "Social Institutions and Economic Development",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Michael Woolcock",
    "Class Day": "F",
    "Class Time": "1:15 PM-4:00 PM"
  },
  {
    "Course ID": "DEV-309-Fall-",
    "Course No": "DEV-309",
    "Section": null,
    "Title": "Development Policy Strategy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Ricardo Hausmann",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DEV-320M-Fall 2-",
    "Course No": "DEV-320M",
    "Section": null,
    "Title": "Scaling Up for Development Impact",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Isabel Guerrero Pulgar",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DEV-325M-January-",
    "Course No": "DEV-325M",
    "Section": null,
    "Title": "Bureaucracy and Policy: Opening the Black Box of Governance",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Adnan Khan",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "9:00 AM-1:00 PM"
  },
  {
    "Course ID": "DEV-338-Fall-",
    "Course No": "DEV-338",
    "Section": null,
    "Title": "Contemporary Developing Countries: Entrepreneurial Solutions to Intractable Problems",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Tarun Khanna",
    "Class Day": "M/W",
    "Class Time": "3:30 PM-5:00 PM"
  },
  {
    "Course ID": "DEV-375-Spring-",
    "Course No": "DEV-375",
    "Section": null,
    "Title": "The Informal Economy: Is Formalization the Answer?",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Martha Chen",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DEV-401Y-Year-",
    "Course No": "DEV-401Y",
    "Section": null,
    "Title": "Applications and Cases in International Development",
    "Credits": "4.00",
    "Term": "Year",
    "Faculty": "Michael Walton, Lant Pritchett",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DEV-501M-January-",
    "Course No": "DEV-501M",
    "Section": null,
    "Title": "Native Americans in the 21st Century: Nation Building I",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Joseph Kalt",
    "Class Day": "T/W/Th/F",
    "Class Time": "10:00 AM-4:30 PM"
  },
  {
    "Course ID": "DEV-502-Spring-",
    "Course No": "DEV-502",
    "Section": null,
    "Title": "Native Americans in the 21st Century: Nation Building II",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Dennis Norman",
    "Class Day": "T",
    "Class Time": "2:00 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-101-Spring-G",
    "Course No": "DPI-101",
    "Section": "G",
    "Title": "Political Institutions and Public Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Thomas Patterson",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-101-Spring-H",
    "Course No": "DPI-101",
    "Section": "H",
    "Title": "Political Institutions and Public Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Matthew Baum",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-101-Spring-I",
    "Course No": "DPI-101",
    "Section": "I",
    "Title": "Political Institutions and Public Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Tarek Masoud",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-101-Spring-J",
    "Course No": "DPI-101",
    "Section": "J",
    "Title": "Political Institutions and Public Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Quinton Mayne",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-117M-Spring 2-",
    "Course No": "DPI-117M",
    "Section": null,
    "Title": "The Evolution of the 21st Century American Presidency: Bush, Obama, and Trump",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Elaine Kamarck",
    "Class Day": "M",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "DPI-120-Spring-",
    "Course No": "DPI-120",
    "Section": null,
    "Title": "The U.S. Congress and Law Making",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "David King",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-132-Fall-",
    "Course No": "DPI-132",
    "Section": null,
    "Title": "Presidents, Politics, and Economic Growth: From FDR to Donald Trump",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Richard Parker",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-150Y-Year-",
    "Course No": "DPI-150Y",
    "Section": null,
    "Title": "Seminar: Democracy, Politics, and Institutions",
    "Credits": "4.00",
    "Term": "Year",
    "Faculty": "Matthew Baum",
    "Class Day": "Th",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "DPI-201-Fall-A",
    "Course No": "DPI-201",
    "Section": "A",
    "Title": "The Responsibilities of Public Action",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Mathias Risse",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-201-Fall-B",
    "Course No": "DPI-201",
    "Section": "B",
    "Title": "The Responsibilities of Public Action",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Christopher Robichaud",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-201-Fall-C",
    "Course No": "DPI-201",
    "Section": "C",
    "Title": "The Responsibilities of Public Action",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Christopher Robichaud",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-201-Fall-D",
    "Course No": "DPI-201",
    "Section": "D",
    "Title": "The Responsibilities of Public Action",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Mathias Risse",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-204-Fall-",
    "Course No": "DPI-204",
    "Section": null,
    "Title": "Seminar in Bioethics",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Frances Kamm",
    "Class Day": "W",
    "Class Time": "4:00 PM-6:00 PM"
  },
  {
    "Course ID": "DPI-216-Spring-",
    "Course No": "DPI-216",
    "Section": null,
    "Title": "Democratic Theory",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Jane Mansbridge",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-218-Spring-",
    "Course No": "DPI-218",
    "Section": null,
    "Title": "Principled Disobedience in Democracies",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Arthur Applbaum",
    "Class Day": "M",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "DPI-227-Fall-",
    "Course No": "DPI-227",
    "Section": null,
    "Title": "Religion in America’s Political Conscience and at the Ballot Box",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": null,
    "Class Day": "T/Th",
    "Class Time": "10:00 AM-11:29 AM"
  },
  {
    "Course ID": "DPI-235-Spring-",
    "Course No": "DPI-235",
    "Section": null,
    "Title": "Economic Justice",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Christopher Robichaud",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DPI-242-Spring-",
    "Course No": "DPI-242",
    "Section": null,
    "Title": "Ignorance, Lies, Hogwash, and Humbug:  The Value of Truth and Knowledge in Democracies",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Christopher Robichaud",
    "Class Day": "M/W",
    "Class Time": "1:00 PM-1:59 PM"
  },
  {
    "Course ID": "DPI-253-Spring-",
    "Course No": "DPI-253",
    "Section": null,
    "Title": "Killing and Letting Die in Public Policy: From A(bortion) to W(ar)",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Frances Kamm",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-305-Fall-",
    "Course No": "DPI-305",
    "Section": null,
    "Title": "Challenges Facing Democracy in the United States",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Alex Keyssar",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-324-Fall-",
    "Course No": "DPI-324",
    "Section": null,
    "Title": "Running for Office and Managing Campaigns",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Steve Jarding",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-330-Fall-A",
    "Course No": "DPI-330",
    "Section": "A",
    "Title": "The Making of a Politician",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Steve Jarding",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-330-Spring-B",
    "Course No": "DPI-330",
    "Section": "B",
    "Title": "The Making of a Politician",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Steve Jarding",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-342-Fall-",
    "Course No": "DPI-342",
    "Section": null,
    "Title": "Religion, Politics, and Public Policy in America",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Richard Parker",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DPI-345M-Spring 1-",
    "Course No": "DPI-345M",
    "Section": null,
    "Title": "Green Politics and Public Policy in a Global Age",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Muriel Rouyer",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-348-Spring-",
    "Course No": "DPI-348",
    "Section": null,
    "Title": "Progressive Alternatives: Institutional Reconstruction Today",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Roberto Mangabeira Unger",
    "Class Day": "T",
    "Class Time": "1:00 PM-3:00 PM"
  },
  {
    "Course ID": "DPI-351M-January-",
    "Course No": "DPI-351M",
    "Section": null,
    "Title": "Lobbying: Theory, Practice, and Simulations",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Mark Fagan",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "9:00 AM-6:00 PM"
  },
  {
    "Course ID": "DPI-365-Spring-",
    "Course No": "DPI-365",
    "Section": null,
    "Title": "Plutocracy, Philanthropy, and the Public Good",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Khalil Muhammad",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-391-Fall-",
    "Course No": "DPI-391",
    "Section": null,
    "Title": "Race, Inequality, and American Democracy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Khalil Muhammad",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-401M-Fall 2-",
    "Course No": "DPI-401M",
    "Section": null,
    "Title": "Institutions and Development",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Ryan Sheely",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-407-Fall-",
    "Course No": "DPI-407",
    "Section": null,
    "Title": "Getting and Keeping Democracy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Scott Mainwaring, Tarek Masoud",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-415-Fall-",
    "Course No": "DPI-415",
    "Section": null,
    "Title": "Comparative Politics and Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Pippa Norris",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-421-Fall-",
    "Course No": "DPI-421",
    "Section": null,
    "Title": "Power Shifts: Understanding Global Change Through History",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Arne Westad",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-425-Fall-",
    "Course No": "DPI-425",
    "Section": null,
    "Title": "U.S. Workers and Workplace Policies",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Holly Fechner",
    "Class Day": "M",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "DPI-431-Fall-",
    "Course No": "DPI-431",
    "Section": null,
    "Title": "Global Europe in the 21st Century: Democracy, Governance, and Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Muriel Rouyer",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DPI-440-Fall-",
    "Course No": "DPI-440",
    "Section": null,
    "Title": "Middle Eastern Politics and Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Tarek Masoud",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-450-Spring-",
    "Course No": "DPI-450",
    "Section": null,
    "Title": "The Political Economy of Transition in China",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Anthony Saich",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "DPI-452-Spring-",
    "Course No": "DPI-452",
    "Section": null,
    "Title": "Restless Empire:  The Past, Present, and Future of Chinese Power",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Arne Westad",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-454-Spring-",
    "Course No": "DPI-454",
    "Section": null,
    "Title": "The Asia-Pacific in Transition",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Jeeyang Rhee Baum",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "DPI-460-Spring-",
    "Course No": "DPI-460",
    "Section": null,
    "Title": "Latin American Politics and Policymaking",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Candelaria Garay",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-515-Spring-",
    "Course No": "DPI-515",
    "Section": null,
    "Title": "Disability Law and Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Michael Stein",
    "Class Day": "W",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "DPI-540M-January-",
    "Course No": "DPI-540M",
    "Section": null,
    "Title": "Combatting Corruption Internationally",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Mark Wolf",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "2:00 PM-5:00 PM"
  },
  {
    "Course ID": "DPI-562-Fall-",
    "Course No": "DPI-562",
    "Section": null,
    "Title": "Public Problems: Advice, Strategy and Analysis",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Archon Fung",
    "Class Day": "Th",
    "Class Time": "4:00 PM-5:59 PM"
  },
  {
    "Course ID": "DPI-563Y-Year-",
    "Course No": "DPI-563Y",
    "Section": null,
    "Title": "Integrated Law/Policy Research and Writing",
    "Credits": "2.00",
    "Term": "Year",
    "Faculty": "Sarah Wald, Archon Fung",
    "Class Day": "F",
    "Class Time": "3:00 PM-5:00 PM"
  },
  {
    "Course ID": "DPI-616-Fall-",
    "Course No": "DPI-616",
    "Section": null,
    "Title": "Public Opinion",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Pippa Norris",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-645-Fall-",
    "Course No": "DPI-645",
    "Section": null,
    "Title": "Race, Politics, and the Media in America: It’s Not Always \"the Economy, Stupid\"",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Andrew Rosenthal",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "DPI-662-Fall-",
    "Course No": "DPI-662",
    "Section": null,
    "Title": "Digital Government: Technology, Policy, and Public Service Innovation",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "David Eaves",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-663-Spring-",
    "Course No": "DPI-663",
    "Section": null,
    "Title": "Tech and Innovation in Government (Field Class)",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Nick Sinai",
    "Class Day": "F",
    "Class Time": "9:00 AM-12:00 PM"
  },
  {
    "Course ID": "DPI-670M-Spring 1-",
    "Course No": "DPI-670M",
    "Section": null,
    "Title": "Preventing Digital Disaster: Why Digital Implementations So Often Go Badly",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Steven Kelman, David Eaves",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "DPI-671M-Spring 2-",
    "Course No": "DPI-671M",
    "Section": null,
    "Title": "Disrupting Bureaucracy: Understanding Recent Efforts in Digital Government",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "David Eaves",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "DPI-674M-Spring 1-",
    "Course No": "DPI-674M",
    "Section": null,
    "Title": "The Internet and Political Campaigns",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Nicco Mele",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-675M-Spring 2-",
    "Course No": "DPI-675M",
    "Section": null,
    "Title": "Media and Journalism in the Digital Age",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Nicco Mele",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-676M-Spring 2-",
    "Course No": "DPI-676M",
    "Section": null,
    "Title": "Designing Government",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Dana Chisnell",
    "Class Day": "F",
    "Class Time": "1:15 PM-4:15 PM"
  },
  {
    "Course ID": "DPI-687-Spring-",
    "Course No": "DPI-687",
    "Section": null,
    "Title": "The Ethics and Governance of Artificial Intelligence",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Jonathan Zittrain",
    "Class Day": "T",
    "Class Time": "5:00 PM-7:59 PM"
  },
  {
    "Course ID": "DPI-691M-January-A",
    "Course No": "DPI-691M",
    "Section": "A",
    "Title": "Programming and Data for Policymakers",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Dhrumil Mehta",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "9:00 AM-5:00 PM"
  },
  {
    "Course ID": "DPI-691M-January-B",
    "Course No": "DPI-691M",
    "Section": "B",
    "Title": "Programming and Data for Policymakers",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Dhrumil Mehta",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "9:00 AM-5:00 PM"
  },
  {
    "Course ID": "DPI-720-Spring-",
    "Course No": "DPI-720",
    "Section": null,
    "Title": "Leaders and Leadership in History",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Moshik Temkin",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-730-Spring-",
    "Course No": "DPI-730",
    "Section": null,
    "Title": "The Past and the Present: Directed Research in History and Public Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Moshik Temkin",
    "Class Day": "M",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "DPI-801-Fall-A",
    "Course No": "DPI-801",
    "Section": "A",
    "Title": "The Arts of Communication",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Marie Danziger",
    "Class Day": "M/W",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "DPI-801-Fall-B",
    "Course No": "DPI-801",
    "Section": "B",
    "Title": "The Arts of Communication",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Timothy Patrick McCarthy",
    "Class Day": "M/W",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "DPI-802M-January-A",
    "Course No": "DPI-802M",
    "Section": "A",
    "Title": "The Arts of Communication",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Holly Weeks",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "9:00 AM-6:00 PM"
  },
  {
    "Course ID": "DPI-802M-Spring 1-B",
    "Course No": "DPI-802M",
    "Section": "B",
    "Title": "The Arts of Communication",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Timothy Patrick McCarthy",
    "Class Day": "T/Th",
    "Class Time": "4:15 PM-8:00 PM"
  },
  {
    "Course ID": "DPI-802M-Spring 1-C",
    "Course No": "DPI-802M",
    "Section": "C",
    "Title": "The Arts of Communication",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Holly Weeks",
    "Class Day": "M/W",
    "Class Time": "4:15 PM-8:00 PM"
  },
  {
    "Course ID": "DPI-802M-Spring 2-D",
    "Course No": "DPI-802M",
    "Section": "D",
    "Title": "The Arts of Communication",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Allison Shapira",
    "Class Day": "M/W",
    "Class Time": "4:15 PM-8:00 PM"
  },
  {
    "Course ID": "DPI-802M-Spring 2-E",
    "Course No": "DPI-802M",
    "Section": "E",
    "Title": "The Arts of Communication",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Timothy Patrick McCarthy",
    "Class Day": "T/Th",
    "Class Time": "4:15 PM-8:00 PM"
  },
  {
    "Course ID": "DPI-810M-Fall 1-A",
    "Course No": "DPI-810M",
    "Section": "A",
    "Title": "Introduction to Writing for Policy and Politics",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Gregory Harris",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-810M-Fall 2-B",
    "Course No": "DPI-810M",
    "Section": "B",
    "Title": "Introduction to Writing for Policy and Politics",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Alexandria Marzano Lesnevich",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DPI-810M-Spring 1-C",
    "Course No": "DPI-810M",
    "Section": "C",
    "Title": "Introduction to Writing for Policy and Politics",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Gregory Harris",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-810M-Spring 2-D",
    "Course No": "DPI-810M",
    "Section": "D",
    "Title": "Introduction to Writing for Policy and Politics",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Alexandria Marzano Lesnevich",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-811M-Fall 2-A",
    "Course No": "DPI-811M",
    "Section": "A",
    "Title": "Advanced Writing for Policy and Politics",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Gregory Harris",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-811M-Spring 2-B",
    "Course No": "DPI-811M",
    "Section": "B",
    "Title": "Advanced Writing for Policy and Politics",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Gregory Harris",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-815M-January-",
    "Course No": "DPI-815M",
    "Section": null,
    "Title": "Revision for Writing About Policy and Politics",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Alexandria Marzano Lesnevich",
    "Class Day": null,
    "Class Time": "2:00 PM-6:00 PM"
  },
  {
    "Course ID": "DPI-820M-Fall 1-A",
    "Course No": "DPI-820M",
    "Section": "A",
    "Title": "Policy Memo Writing for Decision Makers",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Lauren Brodsky",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-820M-Fall 2-B",
    "Course No": "DPI-820M",
    "Section": "B",
    "Title": "Policy Memo Writing for Decision Makers",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Lauren Brodsky",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DPI-820M-Spring 1-C",
    "Course No": "DPI-820M",
    "Section": "C",
    "Title": "Policy Memo Writing for Decision Makers",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Lauren Brodsky",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "DPI-820M-Spring 2-D",
    "Course No": "DPI-820M",
    "Section": "D",
    "Title": "Policy Memo Writing for Decision Makers",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Lauren Brodsky",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DPI-821M-Spring 1-",
    "Course No": "DPI-821M",
    "Section": null,
    "Title": "Long-Form Policy Writing for Decision Makers",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Lauren Brodsky",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "DPI-825M-Fall 2-",
    "Course No": "DPI-825M",
    "Section": null,
    "Title": "Policy Presentations for Decision Makers",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Lauren Brodsky",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-830-Fall-A",
    "Course No": "DPI-830",
    "Section": "A",
    "Title": "Column and Opinion Writing",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Jeffrey Seglin",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DPI-830-Spring-B",
    "Course No": "DPI-830",
    "Section": "B",
    "Title": "Column and Opinion Writing",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Jeffrey Seglin",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "DPI-831M-Fall 2-",
    "Course No": "DPI-831M",
    "Section": null,
    "Title": "Op-Ed Writing",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Josh Burek",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "DPI-835M-Fall 1-A",
    "Course No": "DPI-835M",
    "Section": "A",
    "Title": "Speechwriting",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Stephen Krupin",
    "Class Day": "M",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "DPI-835M-Spring 2-B",
    "Course No": "DPI-835M",
    "Section": "B",
    "Title": "Speechwriting",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Stephen Krupin",
    "Class Day": "M",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "DPI-840M-Spring 2-",
    "Course No": "DPI-840M",
    "Section": null,
    "Title": "Analytical Writing for Policy Journals",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Jerry Lanson",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "DPI-892-Fall-",
    "Course No": "DPI-892",
    "Section": null,
    "Title": "Strategic Communications for Policy Change: Practical Strategies for Influencing a Better World",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Andy Burness",
    "Class Day": "W",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "IGA-100-Spring-",
    "Course No": "IGA-100",
    "Section": null,
    "Title": "International and Global Affairs:Concepts and Applications",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Stephen Walt",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "IGA-103-Fall-",
    "Course No": "IGA-103",
    "Section": null,
    "Title": "Global Governance",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "John Ruggie",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "IGA-107M-Fall 1-",
    "Course No": "IGA-107M",
    "Section": null,
    "Title": "Global Justice",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Kathryn Sikkink",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "IGA-109-Spring-",
    "Course No": "IGA-109",
    "Section": null,
    "Title": "Negotiation and Diplomacy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Nicholas Burns",
    "Class Day": "M/T",
    "Class Time": "1:30 PM-3:00 PM"
  },
  {
    "Course ID": "IGA-112-Fall-",
    "Course No": "IGA-112",
    "Section": null,
    "Title": "The Politics and Ethics of Statecraft",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "J. Bryan Hehir",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "IGA-116-Spring-",
    "Course No": "IGA-116",
    "Section": null,
    "Title": "Great Power Competition in the International System",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Nicholas Burns",
    "Class Day": "W",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "IGA-121-Spring-",
    "Course No": "IGA-121",
    "Section": null,
    "Title": "Religion and World Politics: Connections and Collisions",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "J. Bryan Hehir",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "IGA-145M-Fall 2-",
    "Course No": "IGA-145M",
    "Section": null,
    "Title": "Human Security: People-Centered Global Policy",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Kathryn Sikkink",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "IGA-150Y-Year-",
    "Course No": "IGA-150Y",
    "Section": null,
    "Title": "Seminar: International and Global Affairs",
    "Credits": "4.00",
    "Term": "Year",
    "Faculty": "Matthew Bunn",
    "Class Day": "Th",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "IGA-165M-Spring 1-",
    "Course No": "IGA-165M",
    "Section": null,
    "Title": "Corporate Responsibility and New Governance Models",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Jane Nelson, John Ruggie",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "IGA-211-Fall-",
    "Course No": "IGA-211",
    "Section": null,
    "Title": "Central Challenges of American National Security, Strategy, and the Press",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Graham Allison, David Sanger",
    "Class Day": "M",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "IGA-212M-Spring 1-",
    "Course No": "IGA-212M",
    "Section": null,
    "Title": "Leadership and Management of National Security",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "William Rapp",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "IGA-213-Fall-",
    "Course No": "IGA-213",
    "Section": null,
    "Title": "The Economics of National Security Seminar",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Martin Feldstein",
    "Class Day": "T",
    "Class Time": "6:00 PM-6:59 PM"
  },
  {
    "Course ID": "IGA-219M-Fall 2-",
    "Course No": "IGA-219M",
    "Section": null,
    "Title": "What's Wrong with U.S. Foreign Policy?",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Stephen Walt",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "IGA-220-Spring-",
    "Course No": "IGA-220",
    "Section": null,
    "Title": "The Politics and Ethics of the Use of Force",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "J. Bryan Hehir",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "IGA-224M-Spring 2-",
    "Course No": "IGA-224M",
    "Section": null,
    "Title": "Decision Making in Recent Crises",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Meghan O'Sullivan",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "IGA-227-Spring-",
    "Course No": "IGA-227",
    "Section": null,
    "Title": "Insurgents, Terrorists, and Violence: Causes and Consequences of Civil War",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Dara Kay Cohen",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "IGA-229-Fall-",
    "Course No": "IGA-229",
    "Section": null,
    "Title": "Sex, Violence, and Global Politics",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Dara Kay Cohen",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "IGA-232-Fall-",
    "Course No": "IGA-232",
    "Section": null,
    "Title": "Controlling the World's Most Dangerous Weapons",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "William Tobey, Matthew Bunn",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "IGA-236-Spring-",
    "Course No": "IGA-236",
    "Section": null,
    "Title": "Cybersecurity: Technology, Policy, and Law",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Bruce Schneier",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "IGA-237M-Fall 2-",
    "Course No": "IGA-237M",
    "Section": null,
    "Title": "Future Issues in Cyber-Policy",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Bruce Schneier",
    "Class Day": "T",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "IGA-238-Fall-",
    "Course No": "IGA-238",
    "Section": null,
    "Title": "Technology, Privacy, and the Trans-National Nature of the Internet",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "James Waldo",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "IGA-240-Fall-",
    "Course No": "IGA-240",
    "Section": null,
    "Title": "Cyber and Information Operations:  Technology, Policy, and the Law",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Eric Rosenbach",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "IGA-305M-Fall 1-",
    "Course No": "IGA-305M",
    "Section": null,
    "Title": "The Human Rights of Children and Youth as Citizens, Migrants and Refugees",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Jacqueline Bhabha",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "IGA-342M-Fall 2-",
    "Course No": "IGA-342M",
    "Section": null,
    "Title": "Human Rights Dilemmas in Child Protection",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Jacqueline Bhabha",
    "Class Day": "T/Th",
    "Class Time": "9:45 AM-11:15 AM"
  },
  {
    "Course ID": "IGA-344M-January-",
    "Course No": "IGA-344M",
    "Section": null,
    "Title": "International Perspectives on Justice for Children",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": null,
    "Class Day": "T/W/Th/F",
    "Class Time": "8:00 AM-5:00 PM"
  },
  {
    "Course ID": "IGA-347-Spring-",
    "Course No": "IGA-347",
    "Section": null,
    "Title": "Human Rights and National Security:  The Case of Torture",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Douglas A. Johnson, Alberto Mora",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "IGA-351M-Spring 2-",
    "Course No": "IGA-351M",
    "Section": null,
    "Title": "Human Trafficking and Modern Slavery",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Siddharth Kara",
    "Class Day": "W",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "IGA-353M-January-",
    "Course No": "IGA-353M",
    "Section": null,
    "Title": "Middle East Field Study Course:  Humanitarian Negotiations on the Frontlines",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Claude Bruderlein",
    "Class Day": null,
    "Class Time": null
  },
  {
    "Course ID": "IGA-367M-January-",
    "Course No": "IGA-367M",
    "Section": null,
    "Title": "Preventing Mass Atrocities:  The Security Council and the International Criminal Court",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Luis Moreno Ocampo",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "9:00 AM-1:00 PM"
  },
  {
    "Course ID": "IGA-380M-January-",
    "Course No": "IGA-380M",
    "Section": null,
    "Title": "Human Rights Advocacy Using Video, Social Media, and Participatory Media",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Samuel Gregory",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "1:30 PM-5:30 PM"
  },
  {
    "Course ID": "IGA-385-Fall-",
    "Course No": "IGA-385",
    "Section": null,
    "Title": "Strategizing for Human Rights:  Moving from Ideals to Practice",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Douglas A. Johnson",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "IGA-388-Spring-",
    "Course No": "IGA-388",
    "Section": null,
    "Title": "Nonviolent Resistance in the Age of Authoritarians",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Douglas A. Johnson",
    "Class Day": "T",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "IGA-411-Fall-",
    "Course No": "IGA-411",
    "Section": null,
    "Title": "The Energy-Climate Challenge",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "John Holdren, Henry Lee",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "IGA-412M-Fall 1-",
    "Course No": "IGA-412M",
    "Section": null,
    "Title": "The Geopolitics of Energy",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Meghan O'Sullivan",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "IGA-422-Fall-",
    "Course No": "IGA-422",
    "Section": null,
    "Title": "Global Food Politics and Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Robert Paarlberg",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "IGA-436-Spring-",
    "Course No": "IGA-436",
    "Section": null,
    "Title": "Water Resources Development and Management: Technology, Economics, Institutions",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Kenneth Strzepek",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "IGA-451M-Spring 1-",
    "Course No": "IGA-451M",
    "Section": null,
    "Title": "Controversies in Climate, Energy, and the Media: Improving Public Communication",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Cristine Russell",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "IGA-455M-Spring 1-",
    "Course No": "IGA-455M",
    "Section": null,
    "Title": "Leadership in Environmental Conflicts",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Randolph Wentworth",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "IGA-457M-Spring 2-",
    "Course No": "IGA-457M",
    "Section": null,
    "Title": "International Climate Change Policy",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Robert Stowe",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "IGA-507-Fall-",
    "Course No": "IGA-507",
    "Section": null,
    "Title": "Science and Technology in Domestic and International Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "John Holdren",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "IGA-513-Fall-",
    "Course No": "IGA-513",
    "Section": null,
    "Title": "Science, Power, and Politics",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Sheila Jasanoff",
    "Class Day": "W",
    "Class Time": "2:00 PM-4:00 PM"
  },
  {
    "Course ID": "IGA-515-Spring-",
    "Course No": "IGA-515",
    "Section": null,
    "Title": "Bioethics, Law, and the Life Sciences",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Sheila Jasanoff",
    "Class Day": "M",
    "Class Time": "4:15 PM-6:15 PM"
  },
  {
    "Course ID": "IGA-523-Fall-",
    "Course No": "IGA-523",
    "Section": null,
    "Title": "Innovation for Global Development",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Calestous Juma",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "IGA-528-Spring-",
    "Course No": "IGA-528",
    "Section": null,
    "Title": "Technology and Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "David Keith",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "IGA-615-Fall-",
    "Course No": "IGA-615",
    "Section": null,
    "Title": "Protecting the Homeland(s): The Challenges of Domestic Security",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Juliette Kayyem",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "IGA-662-Spring-",
    "Course No": "IGA-662",
    "Section": null,
    "Title": "The Political Economy of the EU: An International Political Economy Perspective",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Leila Simona Talani",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "IGA-685-Fall-",
    "Course No": "IGA-685",
    "Section": null,
    "Title": "Negotiating U.S. Interests in an Evolving Asia Pacific",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "John Park",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "IGA-956Y-Year-",
    "Course No": "IGA-956Y",
    "Section": null,
    "Title": "Science, Technology, and Society:  Research Seminar",
    "Credits": "4.00",
    "Term": "Year",
    "Faculty": "Sheila Jasanoff",
    "Class Day": "T",
    "Class Time": "12:00 PM-2:00 PM"
  },
  {
    "Course ID": "MLD-102M-Fall 1-A",
    "Course No": "MLD-102M",
    "Section": "A",
    "Title": "Getting Things Done: Management in a Development Context",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Matt Andrews",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-102M-Fall 1-B",
    "Course No": "MLD-102M",
    "Section": "B",
    "Title": "Getting Things Done: Management in a Development Context",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Matt Andrews",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "MLD-103M-Spring 1-",
    "Course No": "MLD-103M",
    "Section": null,
    "Title": "PDIA in Action:  Development Through Facilitated Emergence",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Matt Andrews",
    "Class Day": "M",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "MLD-110-Fall-",
    "Course No": "MLD-110",
    "Section": null,
    "Title": "Strategic Management for Public Purposes",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Peter Zimmerman",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "MLD-115-Spring-",
    "Course No": "MLD-115",
    "Section": null,
    "Title": "Management Matters: Leadership, Strategy and Getting Things Done",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Joseph Bower",
    "Class Day": "W",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "MLD-201-Fall-A",
    "Course No": "MLD-201",
    "Section": "A",
    "Title": "Exercising Leadership: The Politics of Change",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Farayi Chipungu",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "MLD-201-Fall-B",
    "Course No": "MLD-201",
    "Section": "B",
    "Title": "Exercising Leadership: The Politics of Change",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Timothy O'Brien",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "MLD-201-Spring-C",
    "Course No": "MLD-201",
    "Section": "C",
    "Title": "Exercising Leadership: The Politics of Change",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Hugh O'Doherty",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "MLD-220M-Fall 1-A",
    "Course No": "MLD-220M",
    "Section": "A",
    "Title": "Fundamentals of Negotiation Analysis",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Brian Mandell",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "MLD-220M-Fall 1-B",
    "Course No": "MLD-220M",
    "Section": "B",
    "Title": "Fundamentals of Negotiation Analysis",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Brian Mandell",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-220M-Fall 1-C",
    "Course No": "MLD-220M",
    "Section": "C",
    "Title": "Fundamentals of Negotiation Analysis",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Brian Mandell",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "MLD-220M-Fall 1-D",
    "Course No": "MLD-220M",
    "Section": "D",
    "Title": "Fundamentals of Negotiation Analysis",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Brian Mandell",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "MLD-222M-Fall 1-",
    "Course No": "MLD-222M",
    "Section": null,
    "Title": "Negotiation Analysis",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Kessely Hong",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-223M-Fall 2-",
    "Course No": "MLD-223M",
    "Section": null,
    "Title": "Negotiating Across Differences",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Kessely Hong",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-224-Fall-A",
    "Course No": "MLD-224",
    "Section": "A",
    "Title": "Behavioral Science of Negotiations",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Julia Minson",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "MLD-224-Fall-B",
    "Course No": "MLD-224",
    "Section": "B",
    "Title": "Behavioral Science of Negotiations",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Julia Minson",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-280-January-",
    "Course No": "MLD-280",
    "Section": null,
    "Title": "Advanced Workshop in Multiparty Negotiation and Conflict Resolution",
    "Credits": "4.00",
    "Term": "January",
    "Faculty": "Brian Mandell",
    "Class Day": "M/T/W/Th/F/S/Su$",
    "Class Time": "8:00 AM-11:00 PM"
  },
  {
    "Course ID": "MLD-301-Spring-",
    "Course No": "MLD-301",
    "Section": null,
    "Title": "Leadership Decision Making",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Jennifer S. Lerner",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "MLD-304-Spring-A",
    "Course No": "MLD-304",
    "Section": "A",
    "Title": "Science of Behavior Change",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Todd Rogers",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "MLD-304-Spring-B",
    "Course No": "MLD-304",
    "Section": "B",
    "Title": "Science of Behavior Change",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Todd Rogers",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "MLD-310-Fall-",
    "Course No": "MLD-310",
    "Section": null,
    "Title": "Behavioral Science for Inclusive Organizations",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Iris Bohnet",
    "Class Day": "M",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "MLD-325-Fall-",
    "Course No": "MLD-325",
    "Section": null,
    "Title": "Becoming a Leader",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "David Gergen",
    "Class Day": "M",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "MLD-335Y-Year-",
    "Course No": "MLD-335Y",
    "Section": null,
    "Title": "United Kingdom Immersive Field Course: Behavioral Insights",
    "Credits": "4.00",
    "Term": "Year",
    "Faculty": "Michael Luca",
    "Class Day": null,
    "Class Time": null
  },
  {
    "Course ID": "MLD-337Y-Year-",
    "Course No": "MLD-337Y",
    "Section": null,
    "Title": "EC Field Course - US: Behavioral Insights",
    "Credits": "4.00",
    "Term": "Year",
    "Faculty": "Max Bazerman",
    "Class Day": null,
    "Class Time": null
  },
  {
    "Course ID": "MLD-340-Fall-",
    "Course No": "MLD-340",
    "Section": null,
    "Title": "Power and Influence",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Julie Battilana",
    "Class Day": null,
    "Class Time": "11:40 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-342-January-",
    "Course No": "MLD-342",
    "Section": null,
    "Title": "Persuasion: The Science and Art of Effective Influence",
    "Credits": "4.00",
    "Term": "January",
    "Faculty": "Gary Orren",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "8:00 AM-6:00 PM"
  },
  {
    "Course ID": "MLD-352-Fall-",
    "Course No": "MLD-352",
    "Section": null,
    "Title": "The Leadership System: Leaders, Followers, Context",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Barbara Kellerman",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-355M-Fall 1-",
    "Course No": "MLD-355M",
    "Section": null,
    "Title": "Public Narrative: Self, Us, Now",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Marshall Ganz",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "MLD-356M-Fall 2-",
    "Course No": "MLD-356M",
    "Section": null,
    "Title": "Public Narrative: Loss, Difference, Power, and Change",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Marshall Ganz",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "MLD-364-January-",
    "Course No": "MLD-364",
    "Section": null,
    "Title": "Leadership from the Inside Out:  The Personal Capacity to Lead and Stay Alive",
    "Credits": "4.00",
    "Term": "January",
    "Faculty": "Ronald Heifetz",
    "Class Day": "M/T/W/Th/F/S",
    "Class Time": "9:00 AM-5:30 PM"
  },
  {
    "Course ID": "MLD-364M-Spring 2-",
    "Course No": "MLD-364M",
    "Section": null,
    "Title": "Leadership from the Inside Out:  The Personal Capacity to Lead and Stay Alive",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Ronald Heifetz",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "9:00 AM-5:30 PM"
  },
  {
    "Course ID": "MLD-377-Spring-",
    "Course No": "MLD-377",
    "Section": null,
    "Title": "Organizing:  People, Power, Change",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Marshall Ganz",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "MLD-381-Spring-",
    "Course No": "MLD-381",
    "Section": null,
    "Title": "Mitigating and Managing a Crisis",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Juliette Kayyem",
    "Class Day": "M",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "MLD-401M-Fall 1-",
    "Course No": "MLD-401M",
    "Section": null,
    "Title": "Financial Management in Public and Nonprofit Organizations",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Brian Iammartino",
    "Class Day": "M/W",
    "Class Time": "4:15 PM-5:30 PM"
  },
  {
    "Course ID": "MLD-410-Spring-",
    "Course No": "MLD-410",
    "Section": null,
    "Title": "State and Local Financial Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Shelby Chodos",
    "Class Day": "F",
    "Class Time": "1:15 PM-4:00 PM"
  },
  {
    "Course ID": "MLD-411M-Fall 2-",
    "Course No": "MLD-411M",
    "Section": null,
    "Title": "Introduction to Budgeting and Financial Management",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Linda Bilmes",
    "Class Day": "M",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "MLD-412-Spring-",
    "Course No": "MLD-412",
    "Section": null,
    "Title": "Greater Boston Applied Field Lab: Advanced Budgeting, Financial Management and Operations",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Linda Bilmes",
    "Class Day": "M/W",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "MLD-420M-January-",
    "Course No": "MLD-420M",
    "Section": null,
    "Title": "Federal Budget Policy",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Howell Jackson",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "10:00 AM-12:30 PM"
  },
  {
    "Course ID": "MLD-421M-Spring-",
    "Course No": "MLD-421M",
    "Section": null,
    "Title": "Federal Budget Policy – Research Paper",
    "Credits": "2.00",
    "Term": "Spring",
    "Faculty": "Howell Jackson",
    "Class Day": null,
    "Class Time": null
  },
  {
    "Course ID": "MLD-427-Fall-A",
    "Course No": "MLD-427",
    "Section": "A",
    "Title": "Managing Financial Resources in Non Profit Organizations",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "James Honan",
    "Class Day": "M/W",
    "Class Time": "8:30 AM-9:59 AM"
  },
  {
    "Course ID": "MLD-427-Spring-B",
    "Course No": "MLD-427",
    "Section": "B",
    "Title": "Managing Financial Resources in Non Profit Organizations",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "James Honan",
    "Class Day": "T/Th",
    "Class Time": "8:30 AM-9:59 AM"
  },
  {
    "Course ID": "MLD-500-Fall-A",
    "Course No": "MLD-500",
    "Section": "A",
    "Title": "Maximizing Human Capital and Organizational Performance",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Robert Livingston",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-500-Spring-B",
    "Course No": "MLD-500",
    "Section": "B",
    "Title": "Maximizing Human Capital and Organizational Performance",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Robert Livingston",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "MLD-501M-Fall 2-A",
    "Course No": "MLD-501M",
    "Section": "A",
    "Title": "Conflict and Collaboration: Intra- and Inter-group Dynamics",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Hannah Riley Bowles",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "MLD-501M-Fall 2-B",
    "Course No": "MLD-501M",
    "Section": "B",
    "Title": "Conflict and Collaboration: Intra- and Inter-group Dynamics",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Robert Wilkinson",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-501M-Fall 2-C",
    "Course No": "MLD-501M",
    "Section": "C",
    "Title": "Conflict and Collaboration: Intra- and Inter-group Dynamics",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Hannah Riley Bowles",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "MLD-501M-Fall 2-D",
    "Course No": "MLD-501M",
    "Section": "D",
    "Title": "Conflict and Collaboration: Intra- and Inter-group Dynamics",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Robert Wilkinson",
    "Class Day": "M/W",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "MLD-502-Spring-",
    "Course No": "MLD-502",
    "Section": null,
    "Title": "Developing People: Personal and Systemic Capacity Building",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Timothy O'Brien",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-601-Fall-",
    "Course No": "MLD-601",
    "Section": null,
    "Title": "Operations Management",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Mark Fagan",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "MLD-602-Spring-",
    "Course No": "MLD-602",
    "Section": null,
    "Title": "Performance Leadership: Producing Results in Public and Nonprofit Agencies",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Robert Behn",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "MLD-610-Fall-",
    "Course No": "MLD-610",
    "Section": null,
    "Title": "Generating and Using Evidence to Improve the Management of Your Organization",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Julie Boatright Wilson",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "MLD-617M-Spring 2-",
    "Course No": "MLD-617M",
    "Section": null,
    "Title": "Effective Implementation: Learning from Effective Implementers",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Francis Hartmann, Brittany Butler",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-620M-Spring 2-",
    "Course No": "MLD-620M",
    "Section": null,
    "Title": "Urban Innovation:  Concepts and Practices",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Stephen Goldsmith",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-621-Spring-",
    "Course No": "MLD-621",
    "Section": null,
    "Title": "Innovation Field Lab: Public Problem Solving in Massachusetts Cities",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Jorrit de Jong",
    "Class Day": "M",
    "Class Time": "4:15 PM-8:00 PM"
  },
  {
    "Course ID": "MLD-630M-Fall 2-",
    "Course No": "MLD-630M",
    "Section": null,
    "Title": "Government Turnarounds",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Jeffrey Liebman",
    "Class Day": "M/F",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "MLD-635M-Spring 1-",
    "Course No": "MLD-635M",
    "Section": null,
    "Title": "Creating Public Value: The Theory and Practice of Strategic Management in Government",
    "Credits": "2.00",
    "Term": "Spring 1",
    "Faculty": "Mark Moore",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "MLD-829M-Fall 2-",
    "Course No": "MLD-829M",
    "Section": null,
    "Title": "Fundamentals of Entrepreneurial Finance",
    "Credits": "2.00",
    "Term": "Fall 2",
    "Faculty": "Carl Byers",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "MLD-830-Fall-",
    "Course No": "MLD-830",
    "Section": null,
    "Title": "Entrepreneurship and Innovation in the Private and Social Sectors",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Dick Cavanagh",
    "Class Day": "M",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "MLD-831-Spring-",
    "Course No": "MLD-831",
    "Section": null,
    "Title": "Entrepreneurship and Innovation in the Private and Social Sectors (Business Plan Workshop)",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Dick Cavanagh",
    "Class Day": "M",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "MLD-836M-Fall 1-",
    "Course No": "MLD-836M",
    "Section": null,
    "Title": "Social Entrepreneurship/Social Enterprises 101:  How to Go from Start-Up to End Up",
    "Credits": "2.00",
    "Term": "Fall 1",
    "Faculty": "Jim Bildner",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "MLD-840-Spring-",
    "Course No": "MLD-840",
    "Section": null,
    "Title": "Entrepreneurial Finance",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Carl Byers",
    "Class Day": "T",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "SUP-110-Spring-",
    "Course No": "SUP-110",
    "Section": null,
    "Title": "Making the Social Safety Net Work: Policy Debates and Economic Insights",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Mark Shepard",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "SUP-125-Fall-",
    "Course No": "SUP-125",
    "Section": null,
    "Title": "Public Economics: Designing Government Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Martin Feldstein",
    "Class Day": "M/W",
    "Class Time": "2:00 PM-3:30 PM"
  },
  {
    "Course ID": "SUP-150Y-Year-",
    "Course No": "SUP-150Y",
    "Section": null,
    "Title": "Seminar: Social and Urban Policy",
    "Credits": "4.00",
    "Term": "Year",
    "Faculty": "Julie Boatright Wilson",
    "Class Day": "Th",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "SUP-204-Fall-",
    "Course No": "SUP-204",
    "Section": null,
    "Title": "Growth, Inequality, and the Income of Households",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Jason Furman",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "SUP-206-Spring-",
    "Course No": "SUP-206",
    "Section": null,
    "Title": "The Causes and Consequences of Inequality",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "David Deming",
    "Class Day": "M",
    "Class Time": "4:15 PM-7:00 PM"
  },
  {
    "Course ID": "SUP-207-Spring-",
    "Course No": "SUP-207",
    "Section": null,
    "Title": "Social Structure and Culture in the Study of Race and Urban Poverty",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "William Wilson, James Quane",
    "Class Day": "Th",
    "Class Time": "2:00 PM-3:59 PM"
  },
  {
    "Course ID": "SUP-211-Spring-",
    "Course No": "SUP-211",
    "Section": null,
    "Title": "Institutional & Community-Based Strategies to Support Children & Strengthen Families",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Julie Boatright Wilson",
    "Class Day": "T/Th",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "SUP-311-Fall-",
    "Course No": "SUP-311",
    "Section": null,
    "Title": "The Economic Impact of Immigration",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "George Borjas",
    "Class Day": "M/W",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "SUP-321M-Spring 2-",
    "Course No": "SUP-321M",
    "Section": null,
    "Title": "Designing Social Security Systems",
    "Credits": "2.00",
    "Term": "Spring 2",
    "Faculty": "Jo Anne Barnhart",
    "Class Day": "T/Th",
    "Class Time": "2:45 PM-4:00 PM"
  },
  {
    "Course ID": "SUP-322-Fall-",
    "Course No": "SUP-322",
    "Section": null,
    "Title": "Economics of Labor Market Policies",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "George Borjas",
    "Class Day": "M/W",
    "Class Time": "11:45 AM-1:00 PM"
  },
  {
    "Course ID": "SUP-425M-January-",
    "Course No": "SUP-425M",
    "Section": null,
    "Title": "Developing Effective School and Community Interventions for At-Risk Children",
    "Credits": "2.00",
    "Term": "January",
    "Faculty": "Richard Weissbourd",
    "Class Day": "M/T/W/Th/F",
    "Class Time": "1:00 PM-4:00 PM"
  },
  {
    "Course ID": "SUP-427-Spring-",
    "Course No": "SUP-427",
    "Section": null,
    "Title": "Analyzing Education Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Joshua Goodman",
    "Class Day": "M/W",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "SUP-447-Fall-",
    "Course No": "SUP-447",
    "Section": null,
    "Title": "The Politics of American Education",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Paul Peterson",
    "Class Day": "T/Th",
    "Class Time": "11:00 AM-11:59 AM"
  },
  {
    "Course ID": "SUP-448-Fall-",
    "Course No": "SUP-448",
    "Section": null,
    "Title": "The Political Economy of the School",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Paul Peterson",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "SUP-449-Fall-",
    "Course No": "SUP-449",
    "Section": null,
    "Title": "Politics and Education Policy in the U.S.",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Martin West",
    "Class Day": "M/W",
    "Class Time": "10:00 AM-11:59 AM"
  },
  {
    "Course ID": "SUP-450-Spring-",
    "Course No": "SUP-450",
    "Section": null,
    "Title": "The Consequences of Educational Policy Interventions in Developing Countries",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Felipe Barrera-Osorio",
    "Class Day": "T",
    "Class Time": "1:00 PM-3:59 PM"
  },
  {
    "Course ID": "SUP-470-Spring-",
    "Course No": "SUP-470",
    "Section": null,
    "Title": "Strategies and Policies for Narrowing Racial Achievement Gaps",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Ronald Ferguson",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "SUP-490-Spring-",
    "Course No": "SUP-490",
    "Section": null,
    "Title": "Quantitative Methods for Improving Causal Inference in Education Research",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Eric Taylor",
    "Class Day": "M",
    "Class Time": "4:00 PM-6:59 PM"
  },
  {
    "Course ID": "SUP-500-Fall-",
    "Course No": "SUP-500",
    "Section": null,
    "Title": "Introduction to U.S. Health Care Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Sheila Burke",
    "Class Day": "W",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "SUP-572-Fall-",
    "Course No": "SUP-572",
    "Section": null,
    "Title": "The Economics of Health Care Policy",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Joseph P. Newhouse",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "SUP-575-Spring-",
    "Course No": "SUP-575",
    "Section": null,
    "Title": "Political Analysis and Strategy for U.S. Health Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Robert Blendon",
    "Class Day": "M/W",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "SUP-578-Spring-",
    "Course No": "SUP-578",
    "Section": null,
    "Title": "U.S. Healthcare Industry and Regulatory Policy",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Leemore S. Dafny",
    "Class Day": "T/Th",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "SUP-600-Fall-",
    "Course No": "SUP-600",
    "Section": null,
    "Title": "Policymaking in Urban Settings",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "James Carras",
    "Class Day": "T/Th",
    "Class Time": "1:15 PM-2:30 PM"
  },
  {
    "Course ID": "SUP-601-Spring-",
    "Course No": "SUP-601",
    "Section": null,
    "Title": "Urban Politics, Planning, and Development",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Quinton Mayne",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "SUP-651-Fall-",
    "Course No": "SUP-651",
    "Section": null,
    "Title": "Transportation Policy and Planning",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Jose A. Gomez-Ibanez",
    "Class Day": "M/W",
    "Class Time": "8:45 AM-10:00 AM"
  },
  {
    "Course ID": "SUP-653-Spring-",
    "Course No": "SUP-653",
    "Section": null,
    "Title": "Urban Transportation Planning and Implementation",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": null,
    "Class Day": "F",
    "Class Time": "3:00 PM-6:00 PM"
  },
  {
    "Course ID": "SUP-661-Fall-",
    "Course No": "SUP-661",
    "Section": null,
    "Title": "Housing and Urbanization in the United States",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "James Stockard, Jennifer Molinsky",
    "Class Day": "W",
    "Class Time": "2:00 PM-5:00 PM"
  },
  {
    "Course ID": "SUP-662-Spring-",
    "Course No": "SUP-662",
    "Section": null,
    "Title": "Housing and Urbanization in Global Cities",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Alexander von Hoffman",
    "Class Day": "M/W",
    "Class Time": "10:00 AM-11:29 AM"
  },
  {
    "Course ID": "SUP-663-Fall-",
    "Course No": "SUP-663",
    "Section": null,
    "Title": "Land Use and Environmental Law",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Jerold Kayden",
    "Class Day": "M/W",
    "Class Time": "11:30 AM-12:59 PM"
  },
  {
    "Course ID": "SUP-665-Fall-",
    "Course No": "SUP-665",
    "Section": null,
    "Title": "Real Estate Finance and Development Fundamentals for Public and Private Participants",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Edward Marchant",
    "Class Day": "M/W",
    "Class Time": "4:15 PM-5:30 PM"
  },
  {
    "Course ID": "SUP-666-Spring-",
    "Course No": "SUP-666",
    "Section": null,
    "Title": "Affordable and Mixed-Income Housing Development, Finance, and Management",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Edward Marchant",
    "Class Day": "T/Th",
    "Class Time": "8:30 AM-10:00 AM"
  },
  {
    "Course ID": "SUP-668-Spring-",
    "Course No": "SUP-668",
    "Section": null,
    "Title": "Public and Private Development",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Jerold Kayden",
    "Class Day": "M/W",
    "Class Time": "11:30 AM-12:59 PM"
  },
  {
    "Course ID": "SUP-670-Spring-",
    "Course No": "SUP-670",
    "Section": null,
    "Title": "U.S. Housing Markets, Problems and Policies",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Chris Herbert",
    "Class Day": "M/W",
    "Class Time": "8:30 AM-9:59 AM"
  },
  {
    "Course ID": "SUP-710-Spring-",
    "Course No": "SUP-710",
    "Section": null,
    "Title": "Policing, Crime, Legitimacy, and Evidence",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Christopher Winship, Thomas Abt",
    "Class Day": "T/Th",
    "Class Time": "10:15 AM-11:30 AM"
  },
  {
    "Course ID": "SUP-921-Fall-",
    "Course No": "SUP-921",
    "Section": null,
    "Title": "Proseminar on Inequality and Social Policy I",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "David Deming",
    "Class Day": "W",
    "Class Time": "2:00 PM-3:59 PM"
  },
  {
    "Course ID": "SUP-922-Spring-",
    "Course No": "SUP-922",
    "Section": null,
    "Title": "Proseminar on Inequality and Social Policy II",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Alex Keyssar",
    "Class Day": "W",
    "Class Time": "2:00 PM-4:00 PM"
  },
  {
    "Course ID": "SUP-923-Fall-",
    "Course No": "SUP-923",
    "Section": null,
    "Title": "Proseminar on Inequality and Social Policy III",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Maya Sen",
    "Class Day": "M",
    "Class Time": "2:00 PM-4:00 PM"
  },
  {
    "Course ID": "SUP-951-Spring-",
    "Course No": "SUP-951",
    "Section": null,
    "Title": "Doctoral Seminar in Health Economics",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Joseph P. Newhouse",
    "Class Day": "W",
    "Class Time": "4:15 PM-6:00 PM"
  },
  {
    "Course ID": "SUP-957-Fall-",
    "Course No": "SUP-957",
    "Section": null,
    "Title": "Core Course in Health Policy I",
    "Credits": "4.00",
    "Term": "Fall",
    "Faculty": "Joseph P. Newhouse",
    "Class Day": "T/Th",
    "Class Time": "4:15 PM-5:30 PM"
  },
  {
    "Course ID": "SUP-958-Spring-",
    "Course No": "SUP-958",
    "Section": null,
    "Title": "Core Course in Health Policy II",
    "Credits": "4.00",
    "Term": "Spring",
    "Faculty": "Joseph P. Newhouse",
    "Class Day": "T/Th",
    "Class Time": "4:15 PM-6:00 PM"
  }
]

}